[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_SOCKET_URL,VITE_LOVABLE_CONNECTOR_LOGO_DEV_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
